apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocean-node.fullname" . }}
  labels:
    {{- include "ocean-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ocean-node.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
    - name: p2p-tcp4
      port: {{ .Values.service.ports.p2pTcp4 }}
      targetPort: p2p-tcp4
      protocol: TCP
    - name: p2p-ws4
      port: {{ .Values.service.ports.p2pWs4 }}
      targetPort: p2p-ws4
      protocol: TCP
    - name: p2p-tcp6
      port: {{ .Values.service.ports.p2pTcp6 }}
      targetPort: p2p-tcp6
      protocol: TCP
    - name: p2p-ws6
      port: {{ .Values.service.ports.p2pWs6 }}
      targetPort: p2p-ws6
      protocol: TCP
    - name: p2p-wss4
      port: {{ .Values.service.ports.p2pWss4 }}
      targetPort: p2p-wss4
      protocol: TCP
